/**
 * Canonical Thai administrative areas: จังหวัด → อำเภอ/เขต → ตำบล/แขวง, with
 * English names and per-subdistrict postal codes. 77 provinces / 930 districts
 * / 7,452 subdistricts, generated by scripts/generate-thai-admin-areas.mjs
 * from kongvut/thai-province-data. Names are stored WITHOUT prefixes
 * ("บางเขน", not "เขตบางเขน") — matching both the existing profiles convention
 * and the bare forms Flash Express accepts.
 *
 * SERVER-ONLY: the JSON weighs ~485 KB. Import from API routes / lib server
 * code only, never from a 'use client' module — browsers get slices via
 * /api/thai-admin.
 *
 * Terminology guard (three vocabularies collide here):
 *   dataset "district"      = อำเภอ/เขต  = profiles.state       = Flash cityName
 *   dataset "subdistrict"   = ตำบล/แขวง  = profiles.district    = Flash districtName
 * Everything in this file speaks dataset language; callers translate at their
 * boundary (see PATCH /api/profile and lib/flashExpress.ts).
 */

import areasJson from '@/lib/data/thaiAdminAreas.json';
import { areaMatchKey, areaNamesMatch, isBangkokLike, BANGKOK_CANONICAL } from '@/lib/utils/thaiAddressNormalize';

export interface ThaiSubdistrict { t: string; e: string; z: string }
export interface ThaiDistrict { t: string; e: string; s: ThaiSubdistrict[] }
export interface ThaiProvince { t: string; e: string; d: ThaiDistrict[] }

const PROVINCES: ThaiProvince[] = (areasJson as { v: number; provinces: ThaiProvince[] }).provinces;

// ---------------------------------------------------------------------------
// Lookups
// ---------------------------------------------------------------------------

export function findProvince(input: string | null | undefined): ThaiProvince | null {
    if (!input) return null;
    if (isBangkokLike(input)) {
        return PROVINCES.find(p => p.t === BANGKOK_CANONICAL) || null;
    }
    if (!areaMatchKey(input)) return null;
    return (
        PROVINCES.find(p => areaNamesMatch(p.t, input)) ||
        PROVINCES.find(p => areaNamesMatch(p.e, input)) ||
        null
    );
}

export function findDistrict(province: ThaiProvince, input: string | null | undefined): ThaiDistrict | null {
    const key = areaMatchKey(input);
    if (!key) return null;
    const direct =
        province.d.find(d => areaNamesMatch(d.t, input)) ||
        province.d.find(d => areaNamesMatch(d.e, input));
    if (direct) return direct;
    // Real profiles write the provincial-capital district as bare "เมือง" or
    // repeat the province name ("นนทบุรี / นนทบุรี / บางรักน้อย"). Both mean
    // เมือง<จังหวัด>. Bangkok has no เมือง district, so this stays null there.
    if (key === 'เมือง' || key === 'mueang' || areaNamesMatch(input, province.t) || areaNamesMatch(input, province.e)) {
        return province.d.find(d => d.t === `เมือง${province.t}`) || null;
    }
    return null;
}

export function findSubdistrict(district: ThaiDistrict, input: string | null | undefined): ThaiSubdistrict | null {
    if (!areaMatchKey(input)) return null;
    return (
        district.s.find(s => areaNamesMatch(s.t, input)) ||
        district.s.find(s => areaNamesMatch(s.e, input)) ||
        null
    );
}

// Progressive lists for the /api/thai-admin route.
export function listProvinces(): Array<{ t: string; e: string }> {
    return PROVINCES.map(p => ({ t: p.t, e: p.e }));
}

export function listDistricts(provinceInput: string): Array<{ t: string; e: string }> | null {
    const p = findProvince(provinceInput);
    return p ? p.d.map(d => ({ t: d.t, e: d.e })) : null;
}

export function listSubdistricts(provinceInput: string, districtInput: string): ThaiSubdistrict[] | null {
    const p = findProvince(provinceInput);
    const d = p ? findDistrict(p, districtInput) : null;
    return d ? d.s.map(s => ({ ...s })) : null;
}

// ---------------------------------------------------------------------------
// Validation (profile writes)
// ---------------------------------------------------------------------------

export interface ThaiTrioInput {
    province: string | null | undefined;
    district: string | null | undefined;      // อำเภอ/เขต
    subdistrict: string | null | undefined;   // ตำบล/แขวง
}

export type ThaiTrioResult =
    | { status: 'valid' | 'swapped'; canonical: { province: string; district: string; subdistrict: string; postcode: string } }
    | { status: 'invalid' };

/**
 * Validates a province/district/subdistrict trio against the dataset,
 * prefix-insensitively, and detects the khet↔khwaeng swap that Bangkok users
 * (and the pre-fix Google parser) produce. `swapped` means the two lower
 * levels were crossed — canonical has them in the right order.
 */
export function validateThaiAddressTrio(input: ThaiTrioInput): ThaiTrioResult {
    const p = findProvince(input.province);
    if (!p) return { status: 'invalid' };

    const direct = findDistrict(p, input.district);
    const directSub = direct ? findSubdistrict(direct, input.subdistrict) : null;
    if (direct && directSub) {
        return {
            status: 'valid',
            canonical: { province: p.t, district: direct.t, subdistrict: directSub.t, postcode: directSub.z },
        };
    }

    const swappedDistrict = findDistrict(p, input.subdistrict);
    const swappedSub = swappedDistrict ? findSubdistrict(swappedDistrict, input.district) : null;
    if (swappedDistrict && swappedSub) {
        return {
            status: 'swapped',
            canonical: { province: p.t, district: swappedDistrict.t, subdistrict: swappedSub.t, postcode: swappedSub.z },
        };
    }

    return { status: 'invalid' };
}

// ---------------------------------------------------------------------------
// Flash Express resolution (waybill/rate retries)
// ---------------------------------------------------------------------------

// zip -> every (province, district, subdistrict) carrying it. Built lazily —
// most requests never need it.
let zipIndex: Map<string, Array<{ p: ThaiProvince; d: ThaiDistrict; s: ThaiSubdistrict }>> | null = null;
function getZipIndex() {
    if (!zipIndex) {
        zipIndex = new Map();
        for (const p of PROVINCES) {
            for (const d of p.d) {
                for (const s of d.s) {
                    if (!s.z) continue;
                    const arr = zipIndex.get(s.z) || [];
                    arr.push({ p, d, s });
                    zipIndex.set(s.z, arr);
                }
            }
        }
    }
    return zipIndex;
}

export interface FlashLegInput {
    provinceName: string | null | undefined;
    cityName: string | null | undefined;      // อำเภอ/เขต
    districtName: string | null | undefined;  // ตำบล/แขวง
    postalCode: string | null | undefined;
}

export interface ResolvedFlashLeg {
    provinceName: string;
    cityName: string;
    districtName: string;
    /** true when any field differs (after normalization) from the input */
    changed: boolean;
}

/**
 * Best-effort repair of one waybill leg into a trio Flash's region table will
 * accept: canonical spellings, swap correction, then postcode-guided recovery
 * when a name is unmatchable. Returns null only when even the postcode can't
 * anchor a province — callers should then fall back to the provincial-capital
 * substitution (canonicalCapitalForProvince).
 */
export function resolveFlashLeg(input: FlashLegInput): ResolvedFlashLeg | null {
    const zip = (input.postalCode || '').trim();

    let p = findProvince(input.provinceName);
    if (!p && zip) {
        const hits = getZipIndex().get(zip);
        if (hits?.length) p = hits[0].p;
    }
    if (!p) return null;

    let d = findDistrict(p, input.cityName);
    let s = d ? findSubdistrict(d, input.districtName) : null;

    // Swap correction: city slot holds the ตำบล/แขวง and vice versa.
    if (!d || !s) {
        const swapD = findDistrict(p, input.districtName);
        const swapS = swapD ? findSubdistrict(swapD, input.cityName) : null;
        if (swapD && swapS) {
            d = swapD;
            s = swapS;
        }
    }

    // Postcode recovery for an unmatchable city: pick the district carrying
    // this zip, preferring one that matches either input string.
    if (!d && zip) {
        const hits = (getZipIndex().get(zip) || []).filter(h => h.p === p);
        if (hits.length) {
            const cityKey = areaMatchKey(input.cityName);
            const districtKey = areaMatchKey(input.districtName);
            const preferred = hits.find(h =>
                [areaMatchKey(h.d.t), areaMatchKey(h.d.e)].includes(cityKey) ||
                [areaMatchKey(h.s.t), areaMatchKey(h.s.e)].includes(districtKey));
            const hit = preferred || hits[0];
            d = hit.d;
            s = preferred ? hit.s : null;
        }
    }
    if (!d) return null;

    // Subdistrict recovery: any name match, then zip match, then the
    // district's first ตำบล — routing is postcode + detail-address driven, so
    // a same-district stand-in still delivers (see lib/flashExpress.ts).
    if (!s) {
        s = findSubdistrict(d, input.districtName) ||
            findSubdistrict(d, input.cityName) ||
            (zip ? d.s.find(x => x.z === zip) : null) ||
            d.s[0] ||
            null;
    }
    if (!s) return null;

    const changed =
        areaMatchKey(input.provinceName) !== areaMatchKey(p.t) ||
        areaMatchKey(input.cityName) !== areaMatchKey(d.t) ||
        areaMatchKey(input.districtName) !== areaMatchKey(s.t);

    return { provinceName: p.t, cityName: d.t, districtName: s.t, changed };
}

/**
 * The always-valid last-resort trio for a province: the provincial-capital
 * district (เมือง<จังหวัด>, บางรัก for Bangkok) and its first ตำบล. Used when
 * resolveFlashLeg can't repair the address; the parcel still routes by
 * postcode + detail address. Returns null when even the province is
 * unresolvable — fabricating a leg in the wrong province could physically
 * misroute a parcel, so callers should let the region error propagate instead.
 */
export function canonicalCapitalForProvince(provinceInput: string | null | undefined): ResolvedFlashLeg | null {
    const p = findProvince(provinceInput);
    if (!p) return null;
    if (p.t === BANGKOK_CANONICAL) {
        return { provinceName: p.t, cityName: 'บางรัก', districtName: 'บางรัก', changed: true };
    }
    const capital = p.d.find(d => d.t === `เมือง${p.t}`) || p.d[0];
    return { provinceName: p.t, cityName: capital.t, districtName: capital.s[0]?.t || capital.t, changed: true };
}
